steps:
# step 1
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
      '-c',
      'docker pull gcr.io/$PROJECT_ID/capstone-backend:latest || exit 0'
  ]
# step 2
- name: 'gcr.io/cloud-builders/docker'
  args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/capstone-backend:$BRANCH_NAME-$COMMIT_SHA',
      '-t',
      'gcr.io/$PROJECT_ID/capstone-backend:latest',
      '.'
  ]
# step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=capstone-similarity-check'
# step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'set',
    'image',
    'deployment',
    'capstone-backend',
    'capstone-backend=gcr.io/$PROJECT_ID/capstone-backend:$BRANCH_NAME-$COMMIT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=capstone-similarity-check'
#push images to Registry with tag
images: [
    'gcr.io/$PROJECT_ID/capstone-backend:$BRANCH_NAME-$COMMIT_SHA',
    'gcr.io/$PROJECT_ID/capstone-backend:latest',
]