steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/capstone-backend:$BRANCH_NAME-$COMMIT_SHA',
      '-t',
      'gcr.io/$PROJECT_ID/capstone-backend:latest',
      '.'
  ]
images: [
    'gcr.io/$PROJECT_ID/capstone-backend:$BRANCH_NAME-$COMMIT_SHA',
    'gcr.io/$PROJECT_ID/capstone-backend:latest',
]