kind: Service
apiVersion: v1
metadata:
    name: capstone-backend
spec:
    selector:
        run: capstone-backend
    ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
    type: LoadBalancer